// Override \code\modules\mining\lavaland\mining_loot\megafauna\hierophant.dm
/obj/item/hierophant_club
	var/static/active_hiero_clubs = null

/obj/item/hierophant_club/Initialize(mapload)
	. = ..()
	active_hiero_clubs++
	if(active_hiero_clubs > 3)
		return INITIALIZE_HINT_QDEL

/obj/item/hierophant_club/Destroy(force)
	if(active_hiero_clubs > 3)
		new /obj/item/clothing/accessory/pandora_hope(loc)

	active_hiero_clubs--
	return ..()

// Override code\modules\mining\lavaland\mining_loot\megafauna\ash_drake.dm
/obj/item/lava_staff
	var/static/active_lava_staffs = null

/obj/item/lava_staff/Initialize(mapload)
	. = ..()
	active_lava_staffs++
	if(active_lava_staffs > 2)
		return INITIALIZE_HINT_QDEL

/obj/item/lava_staff/Destroy(force)
	if(active_lava_staffs > 2)
		if(prob(50))
			new /obj/item/crusher_trophy/legionnaire_spine(loc)
		else
			new /obj/item/crusher_trophy/broodmother_tongue(loc)

	active_lava_staffs--
	return ..()

// Override code\modules\mining\abandoned_crates.dm
/obj/structure/closet/crate/secure/loot/spawn_loot()
	var/loot = rand(1,100)
	switch(loot)
		if(1 to 5) //5% chance
			new /obj/item/reagent_containers/cup/glass/bottle/rum(src)
			new /obj/item/reagent_containers/cup/glass/bottle/whiskey(src)
			new /obj/item/reagent_containers/cup/glass/bottle/whiskey(src)
			new /obj/item/lighter(src)
			new /obj/item/reagent_containers/cup/glass/bottle/absinthe/premium(src)
			for(var/i in 1 to 3)
				new /obj/item/cigarette/rollie(src)
		if(6 to 10)
			new /obj/item/melee/skateboard/pro(src)
		if(11 to 20)
			new /obj/item/stack/ore/diamond(src, 10)
		if(21 to 25)
			for(var/i in 1 to 5)
				new /obj/item/poster/random_contraband(src)
		if(26 to 30)
			new /obj/item/vending_refill/sovietsoda(src)
			var/obj/item/circuitboard/machine/vendor/board = new (src)
			board.set_type(/obj/machinery/vending/sovietsoda)
		if(31 to 35)
			new /obj/item/seeds/firelemon(src)
		if(36 to 40)
			for(var/i in 1 to 5)
				new /obj/item/toy/snappop/phoenix(src)
		if(41 to 45)
			new /obj/item/modular_computer/pda/clear(src)
		if(46 to 50)
			new /obj/item/storage/box/syndie_kit/chameleon/broken
		if(51 to 52) // 2% chance
			new /obj/item/melee/baton(src)
		if(53 to 54)
			new /obj/item/toy/balloon/corgi(src)
		if(55 to 58)
			var/newitem = pick(subtypesof(/obj/item/toy/mecha))
			new newitem(src)
		if(59 to 62)
			new /obj/item/borg/upgrade/modkit/aoe/mobs(src)
			new /obj/item/clothing/suit/space(src)
			new /obj/item/clothing/head/helmet/space(src)
		if(63 to 64)
			new /obj/item/clothing/shoes/kindle_kicks(src)
		if(65 to 66)
			new /obj/item/clothing/suit/costume/wellworn_shirt/graphic/ian(src)
			new /obj/item/clothing/suit/hooded/ian_costume(src)
		if(67 to 68)
			var/obj/item/gibtonite/free_bomb = new /obj/item/gibtonite(src)
			free_bomb.quality = rand(GIBTONITE_QUALITY_LOW, GIBTONITE_QUALITY_HIGH)
			free_bomb.GibtoniteReaction(null, "A secure loot closet has spawned a live")
		if(69 to 70)
			new /obj/item/stack/ore/bluespace_crystal(src, 5)
		if(71 to 72)
			new /obj/item/toy/plush/snakeplushie(src)
		if(73 to 74)
			new /mob/living/basic/pet/gondola(src)
		if(75 to 76)
			new /obj/item/toy/plush/lizard_plushie(src)
		if(77 to 78)
			new /obj/item/toy/plush/pkplush(src)
		if(79 to 80)
			new /obj/item/toy/plush/goatplushie(src)
		if (81 to 82)
			new /obj/item/toy/plush/shark(src)
		if (83 to 84)
			new /obj/item/toy/plush/beeplushie(src)
		if(85 to 90)
			new /obj/item/defibrillator/compact(src)
		if(91)
			for(var/i in 1 to 30)
				new /mob/living/basic/cockroach(src)
		if(92)
			new /obj/item/katana(src)
		if(93)
			new /obj/item/dnainjector/xraymut(src)
		if(94)
			new /mob/living/basic/mimic/crate(src)
			qdel_on_open = TRUE
		if(95)
			new /obj/item/toy/plush/nukeplushie(src)
		if(96)
			new /obj/item/toy/spinningtoy/dark_matter(src)
		if(97)
			for(var/i in 1 to 4)
				new /obj/item/clothing/mask/balaclava(src)
			new /obj/item/gun/ballistic/shotgun/toy(src)
			new /obj/item/gun/ballistic/automatic/pistol/toy(src)
			new /obj/item/gun/ballistic/automatic/toy(src)
			new /obj/item/gun/ballistic/automatic/l6_saw/toy/unrestricted(src)
			new /obj/item/ammo_box/foambox(src)
		if(98)
			for(var/i in 1 to 3)
				new /mob/living/basic/bee/toxin(src)
		if(99)
			new /obj/item/implanter/sad_trombone(src)
		if(100)
			new /obj/item/melee/skateboard/hoverboard(src)
	spawned_loot = TRUE

// Override \code\game\objects\structures\icemoon\cave_entrance.dm`

/obj/effect/collapsing_demonic_portal/drop_loot()
	visible_message(span_warning("Something slips out of [src]!"))
	var/loot = rand(1, 27)
	switch(loot)
		if(1)
			new /obj/item/clothing/neck/cloak/wolf_coat(loc)
			new /obj/item/gun/magic/wand/teleport(loc)
		if(2)
			new /obj/item/clothing/glasses/godeye(loc)
		if(3)
			new /obj/item/reagent_containers/cup/bottle/potion/flight(loc)
		if(4)
			new /obj/item/organ/heart/cursed/wizard(loc)
		if(5)
			new /obj/item/jacobs_ladder(loc)
		if(6)
			new /obj/item/rod_of_asclepius(loc)
		if(7)
			new /obj/item/warp_cube/red(loc)
		if(8)
			new /obj/item/wisp_lantern(loc)
		if(9)
			new /obj/item/immortality_talisman(loc)
		if(10)
			new /obj/item/book/granter/action/spell/summonitem(loc)
		if(11)
			new /obj/item/clothing/neck/necklace/memento_mori(loc)
		if(12)
			new /obj/item/borg/upgrade/modkit/lifesteal(loc)
			new /obj/item/bedsheet/cult(loc)
		if(13)
			new /obj/item/disk/design_disk/modkit_disc/mob_and_turf_aoe(loc)
		if(14)
			new /obj/item/disk/design_disk/modkit_disc/bounty(loc)
		if(15)
			new /obj/item/slimepotion/slime/sentience(loc)
			new /obj/item/ship_in_a_bottle(loc)
			new /obj/item/oar(loc)
		if(16)
			new /obj/item/shared_storage/red(loc)
		if(17)
			new /obj/item/clothing/gloves/fingerless/punch_mitts(loc)
			new /obj/item/clothing/head/cowboy(loc)
		if(18)
			new /obj/item/soulstone/anybody(loc)
		if(19)
			new /obj/item/disk/design_disk/modkit_disc/resonator_blast(loc)
		if(20)
			new /obj/item/disk/design_disk/modkit_disc/rapid_repeater(loc)
		if(21)
			new /obj/item/slimepotion/transference(loc)
		if(22)
			new /obj/item/slime_extract/adamantine(loc)
		if(23)
			new /obj/item/weldingtool/abductor(loc)
		if(24)
			new /obj/item/book_of_babel(loc)
		if(25)
			new /obj/item/guardian_creator/miner(loc)
		if(26)
			new /obj/item/clothing/shoes/winterboots/ice_boots(loc)
		if(27)
			new /obj/item/book/granter/action/spell/sacredflame(loc)
