name: Signalement de bug
description: Créez un signalement pour aider à reproduire et à résoudre un problème constaté sur Exostation.
title: "[Bug] "
labels: ["bug"]
body:
  - type: input
    id: reporting-version
    attributes:
      label: "Version du client BYOND:"
      description: |
        Votre version de BYOND (cf. About BYOND en haut à gauche dans votre client BYOND).
        Il est très important de l'inclure, en particulier pour les problèmes d'ordre visuel.
      placeholder: "xxx.xxxx"
    validations:
      required: false
  - type: textarea
    id: issue-summary
    attributes:
      label: "Résumé du bug:"
      description: |
        Décrivez brièvement le problème rencontré. Faites des phrases claires, donnez les informations utiles pour retrouver quand et comment votre problème arrive.
      placeholder: |
        "Quand je fais X, Y se passe au lieu de Z."
        "X sur Y map a Z problème."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Reproduction du bug:"
      description: |
        Description des étapes de reproduction en incluant les étapes utiles (map, etc.).
      placeholder: |
        1. Aller à l'endroit X
        2. Faire l'action Y
        3. Observer le résultat Z
    validations:
      required: true
