contact_links:
  - name: Suggestions non-abouties
    url: https://discord.gg/6mbvStH7t5
    about: Les suggestions non-abouties ou devant être discutées au préalable doivent être proposée sur Discord.
